### ISSUE TITLE
Able to access getmessage knowing without of room number just by password only,

### ISSUE THREAD

**Issue by GunarajKhatri** [baibhavanand/TerminalChat#1]
i create room number as 123456 and password world1 in one terminal and in another terminal i enter getmessage command and it asks me to enter room number and password and instead of entering room number in one field i entered password in both fields and i get messages from test1 user of same password which is not good , i guess !!
Demo photos:
![Screenshot from 2020-12-05 21-58-08](https://user-images.githubusercontent.com/49876251/101251125-e2117c80-3745-11eb-9006-9aa2105bb979.png)
![Screenshot from 2020-12-05 21-58-18](https://user-images.githubusercontent.com/49876251/101251152-e473d680-3745-11eb-9dad-26817b47fe0e.png)

Thanks !!

**Comment by baibhavanand** [comment]
@GunarajKhatri , thanks for this report. 
Looking into this right away.

**Comment by GunarajKhatri** [comment]
@baibhavanand ok !! sure:)

**Comment by baibhavanand** [comment]
Hi @GunarajKhatri,
The issue seems to be patched now. Would you mind confirming if the patch works for you?

**Comment by GunarajKhatri** [comment]
yeah i confirmed !! now its fine :)

**Comment by baibhavanand** [comment]
Thanks for confirming the patch and thank you for helping me make Terminal Chat more secure.
Added you in the [thanks page](https://github.com/baibhavanand/TerminalChat/blob/main/thanks.md).
